version: "3.9"
services: 
  monguito: 
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  mimonorepo:
    build: .
    ports: 
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    links: 
      - monguito